baseurl                 = "https://podcast.theunusable.com/"               # Your domain name. Must end with "/"
languageCode            = "en-gb"
title                   = "The Unusable Podcast"
theme                   = "hugo-sam"
pygmentsStyle           = "manni"                     # https://help.farbox.com/pygments.html
pygmentsCodefences      = true
# googleAnalytics       = "xxx"             # Tracking code, eg. "UA-111111111-1"

[params]
    dateform            = "Mon Jan 02, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 EST"
    favicon             = "/sam.ico"
    homepage            = "home"                        # What to call the home page link
    footerText          = "The Unusable Podcast."

# Metadata
    description         = "The Unusable Podcast - Discussions about the importance of usability &amp; UX"            # Max 160 characters show in search results
    twitterCard         = "summary_large_image"         # Card value “summary”, “summary_large_image”, “app”, or “player”
    primaryImage        = "/cover.jpg"                     # Image that shows on Twitter cards and OpenGraph links

#[[params.mainMenu]]
    #link = "/posts"
    #text = "writing"

[[params.mainMenu]]
    link = "/podcasts"
    text = "Episodes"

[[params.mainMenu]]
    link = "/videos"
    text = "Videos"

[[params.mainMenu]]
    link = "/shop"
    text = "Shop"

[[params.mainMenu]]
    link = "/about"
    text = "About the podcast"
    
